### ISSUE TITLE
Perpetually "Windows is loading files"

### ISSUE THREAD

**Issue by pwiegers** [magnetikonline/linuxmicrosoftievirtualmachines#2]
Hi,

I followed the instructions to start a IE10/Win7 VM on Ubuntu. I installed VirtualBox 5.0.24.
Windows is not starting. A black screen with a progress bar appears "Windows is loading files...", then blinks, and starts again. Any thoughts as to what is going wrong?

regards,

Paul

**Comment by magnetikonline** [comment]
Hello @pwiegers 

Looking at this steps? https://github.com/magnetikonline/linuxmicrosoftievirtualmachines#ie10---windows-7

Yeah I have seen this, but it's typically because I didn't setup the VM using the VirtualBox `OVA` export for the import process exactly as specified, since often Windows can get fussy with hardware types/etc.

Can you try another import of the OVA - not touching _any_ hardware settings proposed? If you still get issues - let me know, I'll try on my end.

  Pete

**Comment by pwiegers** [comment]
Hi Pete,

I tried several ones, but the error is always the same. I tried some different HW-settings, starting of course with the recommended settings... the problem appears to be the same any way I try...

regards,

Paul

**Comment by magnetikonline** [comment]
Thanks @pwiegers - leave it with me, I'll give it a download and try out over the weekend.

  Pete

**Comment by magnetikonline** [comment]
Hey @pwiegers,

  just gave this a go - as per the steps here: https://github.com/magnetikonline/linuxmicrosoftievirtualmachines#ie10---windows-7

Worked perfectly - see screenshot:

![selection_001](https://cloud.githubusercontent.com/assets/1818757/16712504/a7460aee-46cc-11e6-9333-12f05f1d08f1.png)

**VirtualBox version:** 5.0.24 r108355 (latest at time of writing)
**Host OS version:** Ubuntu 16.04LTS `Linux magnetik.dev 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Just installed the OVA via import - the _only_ settings I changed was the RAM to 1024MB, and the VM name to `Windows 7 - IE10` to meet my pedantic naming conventions for VMs :smiley: 

 Pete

**Comment by magnetikonline** [comment]
Hey @pwiegers - going to close this now.

If you keep having issues, let me know - but the old "it works on my machine" is at play here for me.
